# Generated by Django 5.1.1 on 2024-10-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_household_household_name_shoppinglist_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shopping_list_id',
            new_name='shopping_list',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='userhousehold',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='userhousehold',
            old_name='user_id',
            new_name='user',
        ),
    ]
