# Generated by Django 5.1.1 on 2024-10-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_rename_shopping_list_id_item_shopping_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='list_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
