# Generated by Django 5.1.1 on 2024-10-02 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
